name: Generate ASCII Art

on:
  push

jobs:
  ascii_job:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v4

    - name: Install cowsay
      run: sudo apt-get install cowsay -y

    - name: Create ASCII art with cowsay
      run: cowsay -f dragon "Who dared to wake me up?" > dragon.txt

    - name: Find the ASCII art file
      run: grep -i "dragon" dragon.txt

    - name: Read the ASCII art file
      run: cat dragon.txt

    - name: List all files
      run: ls -lrta
