name: Generate ASCII Art

on:
  push

jobs:
  build_job:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v4

    - name: Install cowsay
      run: sudo apt-get install cowsay -y
  test_job: 
    needs: build_job
    runs-on: ubuntu-latest
    steps:
    - name: Create ASCII art with cowsay
      run: cowsay -f dragon "Who dared to wake me up?" > dragon.txt

    - name: Find the ASCII art file
      run: grep -i "dragon" dragon.txt || true

    - name: Read the ASCII art file
      run: cat dragon.txt
  deploy_job:
    needs: [test_job]
    runs-on: ubuntu-latest
    steps:
    - name: List all files
      run: ls -lrta
